"""initial schema

Revision ID: 63c7709cfe6c
Revises:
Create Date: 2026-10-09 06:46:44.409110

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "63c7709cfe6c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ratio", sa.Numeric(), nullable=False),
        sa.Column("incoming_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_policy")),
    )
    op.create_table(
        "hard_constraint_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("minimum_rest_hours", sa.Numeric(), nullable=False),
        sa.Column("maximum_daily_hours", sa.Numeric(), nullable=False),
        sa.Column("maximum_weekly_hours", sa.Numeric(), nullable=False),
        sa.Column("prevent_shift_conflict", sa.Boolean(), nullable=False),
        sa.Column("require_matching_role", sa.Boolean(), nullable=False),
        sa.Column("require_matching_skill", sa.Boolean(), nullable=False),
        sa.Column("require_active_staff", sa.Boolean(), nullable=False),
        sa.Column("preserve_minimum_staffing", sa.Boolean(), nullable=False),
        sa.Column("preserve_source_ward_minimum", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hard_constraint_policy")),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    op.create_table(
        "skill",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill")),
    )
    op.create_table(
        "soft_constraint_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("candidate_count_weight", sa.Numeric(), nullable=False),
        sa.Column("consecutive_shift_weight", sa.Numeric(), nullable=False),
        sa.Column("workload_imbalance_weight", sa.Numeric(), nullable=False),
        sa.Column("projected_overtime_weight", sa.Numeric(), nullable=False),
        sa.Column("roster_change_weight", sa.Numeric(), nullable=False),
        sa.Column(
            "candidate_source_priority", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("optimization_priority", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soft_constraint_policy")),
    )
    op.create_table(
        "ward",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ward")),
    )
    op.create_table(
        "shift",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ward_id", sa.BigInteger(), nullable=False),
        sa.Column("patient_count", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shift_type", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["ward_id"], ["ward.id"], name=op.f("fk_shift_ward_id_ward")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shift")),
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("home_ward_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["home_ward_id"], ["ward.id"], name=op.f("fk_staff_home_ward_id_ward")
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_staff_role_id_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
    )
    op.create_table(
        "actors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "(actor_type = 'user') = (staff_id IS NOT NULL)", name=op.f("ck_actors_user_has_staff")
        ),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], name=op.f("fk_actors_staff_id_staff")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors")),
        sa.UniqueConstraint("staff_id", name=op.f("uq_actors_staff_id")),
    )
    op.create_index(
        "uq_actors_name_non_user",
        "actors",
        ["name"],
        unique=True,
        postgresql_where=sa.text("actor_type <> 'user'"),
    )
    op.create_table(
        "attendance",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("check_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("work_minutes", sa.Integer(), nullable=True),
        sa.Column("overtime_minutes", sa.Integer(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_attendance_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance")),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=True),
        sa.Column("line_uid", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_contacts_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_table(
        "roster_assignment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("shift_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("assignment_type", sa.Text(), nullable=False),
        sa.Column("candidate_source", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shift.id"], name=op.f("fk_roster_assignment_shift_id_shift")
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_roster_assignment_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roster_assignment")),
    )
    op.create_table(
        "staff_skill",
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("skill_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name=op.f("fk_staff_skill_skill_id_skill")
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_staff_skill_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("staff_id", "skill_id", name=op.f("pk_staff_skill")),
    )
    op.create_table(
        "staff_unavailability",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_staff_unavailability_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_unavailability")),
    )
    op.create_table(
        "staff_working_time_snapshot",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("hours_today", sa.Numeric(), nullable=False),
        sa.Column("hours_this_week", sa.Numeric(), nullable=False),
        sa.Column("rest_hours", sa.Numeric(), nullable=False),
        sa.Column("overtime_hours", sa.Numeric(), nullable=False),
        sa.Column("consecutive_shifts", sa.Integer(), nullable=False),
        sa.Column("consecutive_night_shifts", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_staff_working_time_snapshot_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_working_time_snapshot")),
    )
    op.create_table(
        "staffing_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("shift_id", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(event_type IN ('ASSIGNMENT_CANCELLED', 'STAFF_UNAVAILABLE'))"
            " = (staff_id IS NOT NULL)",
            name=op.f("ck_staffing_events_staff_id_matches_event_group"),
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shift.id"], name=op.f("fk_staffing_events_shift_id_shift")
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_staffing_events_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staffing_events")),
    )
    op.create_table(
        "staffing_requirements",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("shift_id", sa.BigInteger(), nullable=False),
        sa.Column("required_staff", sa.Integer(), nullable=False),
        sa.Column("minimum_staff", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shift.id"], name=op.f("fk_staffing_requirements_shift_id_shift")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staffing_requirements")),
    )
    op.create_table(
        "staffing_cases",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("shift_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("required_replacement_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["staffing_events.id"],
            name=op.f("fk_staffing_cases_event_id_staffing_events"),
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shift.id"], name=op.f("fk_staffing_cases_shift_id_shift")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staffing_cases")),
    )
    op.create_table(
        "staffing_requirement_role",
        sa.Column("staffing_requirement_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_staffing_requirement_role_role_id_role")
        ),
        sa.ForeignKeyConstraint(
            ["staffing_requirement_id"],
            ["staffing_requirements.id"],
            name=op.f("fk_staffing_requirement_role_staffing_requirement_id_staffing_requirements"),
        ),
        sa.PrimaryKeyConstraint(
            "staffing_requirement_id", "role_id", name=op.f("pk_staffing_requirement_role")
        ),
    )
    op.create_table(
        "staffing_requirement_skill",
        sa.Column("staffing_requirement_id", sa.BigInteger(), nullable=False),
        sa.Column("skill_id", sa.BigInteger(), nullable=False),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name=op.f("fk_staffing_requirement_skill_skill_id_skill")
        ),
        sa.ForeignKeyConstraint(
            ["staffing_requirement_id"],
            ["staffing_requirements.id"],
            name=op.f(
                "fk_staffing_requirement_skill_staffing_requirement_id_staffing_requirements"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "staffing_requirement_id", "skill_id", name=op.f("pk_staffing_requirement_skill")
        ),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_audit_log_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["staffing_cases.id"], name=op.f("fk_audit_log_case_id_staffing_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "candidate_plans",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("solver_status", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("execution_time_ms", sa.Integer(), nullable=False),
        sa.Column("objective_score", sa.Numeric(), nullable=True),
        sa.Column("solver_version", sa.Text(), nullable=False),
        sa.Column("hard_constraint_policy_id", sa.BigInteger(), nullable=False),
        sa.Column("soft_constraint_policy_id", sa.BigInteger(), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["staffing_cases.id"],
            name=op.f("fk_candidate_plans_case_id_staffing_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["hard_constraint_policy_id"],
            ["hard_constraint_policy.id"],
            name=op.f("fk_candidate_plans_hard_constraint_policy_id_hard_constraint_policy"),
        ),
        sa.ForeignKeyConstraint(
            ["soft_constraint_policy_id"],
            ["soft_constraint_policy.id"],
            name=op.f("fk_candidate_plans_soft_constraint_policy_id_soft_constraint_policy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_plans")),
    )
    op.create_table(
        "staffing_gap",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("staffing_requirement_id", sa.BigInteger(), nullable=False),
        sa.Column("headcount_gap", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["staffing_cases.id"], name=op.f("fk_staffing_gap_case_id_staffing_cases")
        ),
        sa.ForeignKeyConstraint(
            ["staffing_requirement_id"],
            ["staffing_requirements.id"],
            name=op.f("fk_staffing_gap_staffing_requirement_id_staffing_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staffing_gap")),
    )
    op.create_table(
        "structured_handover",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("shift_id", sa.BigInteger(), nullable=False),
        sa.Column("incoming_staff_id", sa.BigInteger(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["staffing_cases.id"],
            name=op.f("fk_structured_handover_case_id_staffing_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["incoming_staff_id"],
            ["staff.id"],
            name=op.f("fk_structured_handover_incoming_staff_id_staff"),
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shift.id"], name=op.f("fk_structured_handover_shift_id_shift")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_structured_handover")),
    )
    op.create_table(
        "candidate_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("proposed_shift_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["candidate_plans.id"],
            name=op.f("fk_candidate_items_plan_id_candidate_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["proposed_shift_id"],
            ["shift.id"],
            name=op.f("fk_candidate_items_proposed_shift_id_shift"),
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["staff.id"], name=op.f("fk_candidate_items_staff_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_items")),
    )
    op.create_table(
        "staffing_gap_role",
        sa.Column("gap_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column("gap_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gap_id"], ["staffing_gap.id"], name=op.f("fk_staffing_gap_role_gap_id_staffing_gap")
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_staffing_gap_role_role_id_role")
        ),
        sa.PrimaryKeyConstraint("gap_id", "role_id", name=op.f("pk_staffing_gap_role")),
    )
    op.create_table(
        "staffing_gap_skill",
        sa.Column("gap_id", sa.BigInteger(), nullable=False),
        sa.Column("skill_id", sa.BigInteger(), nullable=False),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column("gap_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gap_id"], ["staffing_gap.id"], name=op.f("fk_staffing_gap_skill_gap_id_staffing_gap")
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name=op.f("fk_staffing_gap_skill_skill_id_skill")
        ),
        sa.PrimaryKeyConstraint("gap_id", "skill_id", name=op.f("pk_staffing_gap_skill")),
    )
    op.create_table(
        "approval_request",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("candidate_item_id", sa.BigInteger(), nullable=False),
        sa.Column("required_approver_role", sa.BigInteger(), nullable=True),
        sa.Column("approval_mode", sa.Text(), nullable=False),
        sa.Column("is_pending", sa.Boolean(), nullable=False),
        sa.Column("approver_id", sa.BigInteger(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approver_id"], ["staff.id"], name=op.f("fk_approval_request_approver_id_staff")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_item_id"],
            ["candidate_items.id"],
            name=op.f("fk_approval_request_candidate_item_id_candidate_items"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["staffing_cases.id"],
            name=op.f("fk_approval_request_case_id_staffing_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["required_approver_role"],
            ["role.id"],
            name=op.f("fk_approval_request_required_approver_role_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_request")),
    )
    op.create_table(
        "candidate_outreach",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("candidate_item_id", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_item_id"],
            ["candidate_items.id"],
            name=op.f("fk_candidate_outreach_candidate_item_id_candidate_items"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["staffing_cases.id"],
            name=op.f("fk_candidate_outreach_case_id_staffing_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_outreach")),
    )
    op.create_table(
        "safety_validation",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("candidate_item_id", sa.BigInteger(), nullable=False),
        sa.Column("hard_constraint_policy_id", sa.BigInteger(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("validation_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_item_id"],
            ["candidate_items.id"],
            name=op.f("fk_safety_validation_candidate_item_id_candidate_items"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["staffing_cases.id"],
            name=op.f("fk_safety_validation_case_id_staffing_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["hard_constraint_policy_id"],
            ["hard_constraint_policy.id"],
            name=op.f("fk_safety_validation_hard_constraint_policy_id_hard_constraint_policy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_validation")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("safety_validation")
    op.drop_table("candidate_outreach")
    op.drop_table("approval_request")
    op.drop_table("staffing_gap_skill")
    op.drop_table("staffing_gap_role")
    op.drop_table("candidate_items")
    op.drop_table("structured_handover")
    op.drop_table("staffing_gap")
    op.drop_table("candidate_plans")
    op.drop_table("audit_log")
    op.drop_table("staffing_requirement_skill")
    op.drop_table("staffing_requirement_role")
    op.drop_table("staffing_cases")
    op.drop_table("staffing_requirements")
    op.drop_table("staffing_events")
    op.drop_table("staff_working_time_snapshot")
    op.drop_table("staff_unavailability")
    op.drop_table("staff_skill")
    op.drop_table("roster_assignment")
    op.drop_table("contacts")
    op.drop_table("attendance")
    op.drop_index(
        "uq_actors_name_non_user",
        table_name="actors",
        postgresql_where=sa.text("actor_type <> 'user'"),
    )
    op.drop_table("actors")
    op.drop_table("staff")
    op.drop_table("shift")
    op.drop_table("ward")
    op.drop_table("soft_constraint_policy")
    op.drop_table("skill")
    op.drop_table("role")
    op.drop_table("hard_constraint_policy")
    op.drop_table("approval_policy")
    # ### end Alembic commands ###
